
var PhotoPayWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(PhotoPayWasmSDK) {
  PhotoPayWasmSDK = PhotoPayWasmSDK || {};


var k;k||(k=typeof PhotoPayWasmSDK !== 'undefined' ? PhotoPayWasmSDK : {});var aa,ba;k.ready=new Promise(function(a,b){aa=a;ba=b});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in k)k.hasOwnProperty(da)&&(ca[da]=k[da]);var ea="./this.program";function fa(a,b){throw b;}var ha="object"===typeof window,ia="function"===typeof importScripts,p="",ja;
if(ha||ia)ia?p=self.location.href:"undefined"!==typeof document&&document.currentScript&&(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),p=0!==p.indexOf("blob:")?p.substr(0,p.lastIndexOf("/")+1):"",ia&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ka=k.print||console.log.bind(console),r=k.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(k[da]=ca[da]);ca=null;
k.thisProgram&&(ea=k.thisProgram);k.quit&&(fa=k.quit);var la;k.wasmBinary&&(la=k.wasmBinary);var noExitRuntime=k.noExitRuntime||!0;"object"!==typeof WebAssembly&&y("no native wasm support detected");var ma,oa=!1,pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?qa(A,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function ta(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&E[c];)++c;c<<=1;if(32<c-a&&sa)return sa.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ua[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function va(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ua[b>>1]=a.charCodeAt(e),b+=2;ua[b>>1]=0;return b-d}function wa(a){return 2*a.length}function xa(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function ya(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Aa(a){var b=ra(a)+1,c=Ba(b);c&&B(a,I,c,b);return c}var Ca,I,A,ua,E,F,K,Da,Ea;
function Fa(){var a=ma.buffer;Ca=a;k.HEAP8=I=new Int8Array(a);k.HEAP16=ua=new Int16Array(a);k.HEAP32=F=new Int32Array(a);k.HEAPU8=A=new Uint8Array(a);k.HEAPU16=E=new Uint16Array(a);k.HEAPU32=K=new Uint32Array(a);k.HEAPF32=Da=new Float32Array(a);k.HEAPF64=Ea=new Float64Array(a)}var M,Ga=[],Ha=[],Ja=[];function Ka(){var a=k.preRun.shift();Ga.unshift(a)}var La=0,Ma=null,Na=null;function Oa(){La++;k.monitorRunDependencies&&k.monitorRunDependencies(La)}
function Pa(){La--;k.monitorRunDependencies&&k.monitorRunDependencies(La);if(0==La&&(null!==Ma&&(clearInterval(Ma),Ma=null),Na)){var a=Na;Na=null;a()}}k.preloadedImages={};k.preloadedAudios={};function y(a){if(k.onAbort)k.onAbort(a);a+="";r(a);oa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Qa(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="PhotoPayWasmSDK.wasm";
if(!Qa()){var Ra=N;N=k.locateFile?k.locateFile(Ra,p):p+Ra}function Sa(){var a=N;try{if(a==N&&la)return new Uint8Array(la);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}function Ta(){return la||!ha&&!ia||"function"!==typeof fetch?Promise.resolve().then(function(){return Sa()}):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return Sa()})}
var O,P,Ua={255029:function(a){a=z(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},255165:function(a,b,c,d){a=z(a);b=z(b);c=z(c);d=z(d);throw Error(a+b+c+d);},255381:function(a,b){a=z(a);b=z(b);throw Error(a+b);},255491:function(a,b){a=z(a);b=z(b);console.log(a+b)},255589:function(a){throw Error(z(a));},255632:function(){throw Error("Unable to perform that operation while recognizer is in use!");},255715:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},255798:function(){throw Error("Unable to perform that operation while recognizer is in use!");},255881:function(){throw Error("Unable to perform that operation while recognizer is in use!");},255964:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256047:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256130:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256213:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},256296:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256379:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256462:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256545:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256628:function(){throw Error("Unable to perform that operation while recognizer is in use!");},256711:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},256794:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function Va(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(k);else{var c=b.xc;"number"===typeof c?void 0===b.pb?M.get(c)():M.get(c)(b.pb):c(void 0===b.pb?null:b.pb)}}}
function Wa(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);F[Xa()>>2]=60*f;F[Ya()>>2]=Number(b!=e);c=a(c);d=a(d);c=Aa(c);d=Aa(d);e<b?(F[Za()>>2]=c,F[Za()+4>>2]=d):(F[Za()>>2]=d,F[Za()+4>>2]=c)}var $a;
function ab(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function bb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ab(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function cb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function db(a){if("/"===a)return"/";a=bb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function eb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){y("randomDevice")}}
function fb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ab(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var gb=[];function hb(a,b){gb[a]={input:[],Ca:[],Va:b};ib(a,jb)}
var jb={open:function(a){var b=gb[a.node.Za];if(!b)throw new Q(43);a.Ga=b;a.seekable=!1},close:function(a){a.Ga.Va.flush(a.Ga)},flush:function(a){a.Ga.Va.flush(a.Ga)},read:function(a,b,c,d){if(!a.Ga||!a.Ga.Va.Eb)throw new Q(60);for(var e=0,f=0;f<d;f++){try{var g=a.Ga.Va.Eb(a.Ga)}catch(l){throw new Q(29);}if(void 0===g&&0===e)throw new Q(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Ga||!a.Ga.Va.ub)throw new Q(60);try{for(var e=
0;e<d;e++)a.Ga.Va.ub(a.Ga,b[c+e])}catch(f){throw new Q(29);}d&&(a.node.timestamp=Date.now());return e}},lb={Eb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=kb(b,!0)}return a.input.shift()},ub:function(a,b){null===b||10===b?(ka(qa(a.Ca,0)),a.Ca=[]):0!=b&&a.Ca.push(b)},flush:function(a){a.Ca&&0<a.Ca.length&&
(ka(qa(a.Ca,0)),a.Ca=[])}},mb={ub:function(a,b){null===b||10===b?(r(qa(a.Ca,0)),a.Ca=[]):0!=b&&a.Ca.push(b)},flush:function(a){a.Ca&&0<a.Ca.length&&(r(qa(a.Ca,0)),a.Ca=[])}};function nb(a){a=65536*Math.ceil(a/65536);var b=ob(65536,a);if(!b)return 0;A.fill(0,b,b+a);return b}
var R={La:null,Oa:function(){return R.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.La||(R.La={dir:{node:{Ka:R.va.Ka,Ma:R.va.Ma,Xa:R.va.Xa,gb:R.va.gb,Jb:R.va.Jb,Lb:R.va.Lb,Kb:R.va.Kb,Ib:R.va.Ib,kb:R.va.kb},stream:{Sa:R.wa.Sa}},file:{node:{Ka:R.va.Ka,Ma:R.va.Ma},stream:{Sa:R.wa.Sa,read:R.wa.read,write:R.wa.write,yb:R.wa.yb,hb:R.wa.hb,jb:R.wa.jb}},link:{node:{Ka:R.va.Ka,Ma:R.va.Ma,$a:R.va.$a},stream:{}},zb:{node:{Ka:R.va.Ka,Ma:R.va.Ma},
stream:pb}});c=qb(a,b,c,d);16384===(c.mode&61440)?(c.va=R.La.dir.node,c.wa=R.La.dir.stream,c.xa={}):32768===(c.mode&61440)?(c.va=R.La.file.node,c.wa=R.La.file.stream,c.Aa=0,c.xa=null):40960===(c.mode&61440)?(c.va=R.La.link.node,c.wa=R.La.link.stream):8192===(c.mode&61440)&&(c.va=R.La.zb.node,c.wa=R.La.zb.stream);c.timestamp=Date.now();a&&(a.xa[b]=c,a.timestamp=c.timestamp);return c},yc:function(a){return a.xa?a.xa.subarray?a.xa.subarray(0,a.Aa):new Uint8Array(a.xa):new Uint8Array(0)},Bb:function(a,
b){var c=a.xa?a.xa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.xa,a.xa=new Uint8Array(b),0<a.Aa&&a.xa.set(c.subarray(0,a.Aa),0))},mc:function(a,b){if(a.Aa!=b)if(0==b)a.xa=null,a.Aa=0;else{var c=a.xa;a.xa=new Uint8Array(b);c&&a.xa.set(c.subarray(0,Math.min(b,a.Aa)));a.Aa=b}},va:{Ka:function(a){var b={};b.Rb=8192===(a.mode&61440)?a.id:1;b.sb=a.id;b.mode=a.mode;b.hc=1;b.uid=0;b.Zb=0;b.Za=a.Za;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.Aa:40960===
(a.mode&61440)?a.link.length:0;b.Mb=new Date(a.timestamp);b.ec=new Date(a.timestamp);b.Qb=new Date(a.timestamp);b.Nb=4096;b.Ob=Math.ceil(b.size/b.Nb);return b},Ma:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&R.mc(a,b.size)},Xa:function(){throw rb[44];},gb:function(a,b,c,d){return R.createNode(a,b,c,d)},Jb:function(a,b,c){if(16384===(a.mode&61440)){try{var d=sb(b,c)}catch(f){}if(d)for(var e in d.xa)throw new Q(55);}delete a.parent.xa[a.name];
a.parent.timestamp=Date.now();a.name=c;b.xa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Lb:function(a,b){delete a.xa[b];a.timestamp=Date.now()},Kb:function(a,b){var c=sb(a,b),d;for(d in c.xa)throw new Q(55);delete a.xa[b];a.timestamp=Date.now()},Ib:function(a){var b=[".",".."],c;for(c in a.xa)a.xa.hasOwnProperty(c)&&b.push(c);return b},kb:function(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},$a:function(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},wa:{read:function(a,
b,c,d,e){var f=a.node.xa;if(e>=a.node.Aa)return 0;a=Math.min(a.node.Aa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===I.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.xa||a.xa.subarray)){if(f)return a.xa=b.subarray(c,c+d),a.Aa=d;if(0===a.Aa&&0===e)return a.xa=b.slice(c,c+d),a.Aa=d;if(e+d<=a.Aa)return a.xa.set(b.subarray(c,c+d),e),d}R.Bb(a,e+d);if(a.xa.subarray&&b.subarray)a.xa.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.xa[e+f]=b[c+f];a.Aa=Math.max(a.Aa,e+d);return d},Sa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Aa);if(0>b)throw new Q(28);return b},yb:function(a,b,c){R.Bb(a.node,b+c);a.node.Aa=Math.max(a.node.Aa,b+c)},hb:function(a,b,c,d,e,f){if(0!==b)throw new Q(28);if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.xa;if(f&2||a.buffer!==Ca){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;c=
nb(c);if(!c)throw new Q(48);I.set(a,c)}else d=!1,c=a.byteOffset;return{za:c,ob:d}},jb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Q(43);if(e&2)return 0;R.wa.write(a,b,0,d,c,!1);return 0}}},tb=null,ub={},vb=[],wb=1,xb=null,yb=!0,zb={},Q=null,rb={};
function Ab(a,b){a=fb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Db:!0,wb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.wb)throw new Q(32);a=ab(a.split("/").filter(function(g){return!!g}),!1);var e=tb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=sb(e,a[d]);c=bb(c+"/"+a[d]);e.ib&&(!f||f&&b.Db)&&(e=e.ib.root);if(!f||b.qb)for(f=0;40960===(e.mode&61440);)if(e=Bb(c),c=fb(cb(c),e),e=Ab(c,{wb:b.wb}).node,40<f++)throw new Q(32);}return{path:c,node:e}}
function Cb(a){for(var b;;){if(a===a.parent)return a=a.Oa.Fb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Db(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%xb.length}function sb(a,b){var c;if(c=(c=Eb(a,"x"))?c:a.va.Xa?0:2)throw new Q(c,a);for(c=xb[Db(a.id,b)];c;c=c.fc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.va.Xa(a,b)}
function qb(a,b,c,d){a=new Fb(a,b,c,d);b=Db(a.parent.id,a.name);a.fc=xb[b];return xb[b]=a}var Gb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Hb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Eb(a,b){if(yb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ib(a,b){try{return sb(a,b),20}catch(c){}return Eb(a,"wx")}
function Jb(){var a=4096;for(var b=0;b<=a;b++)if(!vb[b])return b;throw new Q(33);}function Kb(a){Lb||(Lb=function(){},Lb.prototype={object:{get:function(){return this.node},set:function(d){this.node=d}}});var b=new Lb,c;for(c in a)b[c]=a[c];a=b;b=Jb();a.Na=b;return vb[b]=a}var pb={open:function(a){a.wa=ub[a.node.Za].wa;a.wa.open&&a.wa.open(a)},Sa:function(){throw new Q(70);}};function ib(a,b){ub[a]={wa:b}}
function Mb(a,b){var c="/"===b,d=!b;if(c&&tb)throw new Q(10);if(!c&&!d){var e=Ab(b,{Db:!1});b=e.path;e=e.node;if(e.ib)throw new Q(10);if(16384!==(e.mode&61440))throw new Q(54);}b={type:a,Ac:{},Fb:b,dc:[]};a=a.Oa(b);a.Oa=b;b.root=a;c?tb=a:e&&(e.ib=b,e.Oa&&e.Oa.dc.push(b))}function Nb(a,b,c){var d=Ab(a,{parent:!0}).node;a=db(a);if(!a||"."===a||".."===a)throw new Q(28);var e=Ib(d,a);if(e)throw new Q(e);if(!d.va.gb)throw new Q(63);return d.va.gb(d,a,b,c)}function S(a){return Nb(a,16895,0)}
function Ob(a,b,c){"undefined"===typeof c&&(c=b,b=438);Nb(a,b|8192,c)}function Pb(a,b){if(!fb(a))throw new Q(44);var c=Ab(b,{parent:!0}).node;if(!c)throw new Q(44);b=db(b);var d=Ib(c,b);if(d)throw new Q(d);if(!c.va.kb)throw new Q(63);c.va.kb(c,b,a)}function Bb(a){a=Ab(a).node;if(!a)throw new Q(44);if(!a.va.$a)throw new Q(28);return fb(Cb(a.parent),a.va.$a(a))}
function Qb(a,b,c){if(""===a)throw new Q(44);if("string"===typeof b){var d=Gb[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=bb(a);try{e=Ab(a,{qb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new Q(20);}else e=Nb(a,c,0),d=!0;if(!e)throw new Q(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new Q(54);if(!d&&(c=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Hb(b)||b&512)?31:Eb(e,Hb(b)):44))throw new Q(c);if(b&512){c=e;c="string"===typeof c?Ab(c,{qb:!0}).node:c;if(!c.va.Ma)throw new Q(63);if(16384===(c.mode&61440))throw new Q(31);if(32768!==(c.mode&61440))throw new Q(28);if(d=Eb(c,"w"))throw new Q(d);c.va.Ma(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Kb({node:e,path:Cb(e),flags:b,seekable:!0,position:0,wa:e.wa,wc:[],error:!1});e.wa.open&&e.wa.open(e);!k.logReadFiles||b&1||(Rb||(Rb={}),a in Rb||(Rb[a]=1,r("FS.trackingDelegate error on read file: "+
a)));try{zb.onOpenFile&&(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),zb.onOpenFile(a,c))}catch(f){r("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}return e}function Sb(a,b,c){if(null===a.Na)throw new Q(8);if(!a.seekable||!a.wa.Sa)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.wa.Sa(a,b,c);a.wc=[]}
function Tb(){Q||(Q=function(a,b){this.node=b;this.nc=function(c){this.Qa=c};this.nc(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(function(a){rb[a]=new Q(a);rb[a].stack="<generic error, no stack>"}))}var Ub;function Vb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Wb(a,b,c){a=bb("/dev/"+a);var d=Vb(!!b,!!c);Xb||(Xb=64);var e=Xb++<<8|0;ib(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,g,l,m){for(var n=0,q=0;q<m;q++){try{var v=b()}catch(w){throw new Q(29);}if(void 0===v&&0===n)throw new Q(6);if(null===v||void 0===v)break;n++;g[l+q]=v}n&&(f.node.timestamp=Date.now());return n},write:function(f,g,l,m){for(var n=0;n<m;n++)try{c(g[l+n])}catch(q){throw new Q(29);}m&&(f.node.timestamp=Date.now());return n}});
Ob(a,d,e)}var Xb,Yb={},Lb,Rb,Zb={},$b=void 0;function ac(a){a=vb[a];if(!a)throw new Q(8);return a}var bc={};function cc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function dc(a){return this.fromWireType(K[a>>2])}var ec={},fc={},gc={};function hc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function ic(a,b){a=hc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function jc(a){var b=Error,c=ic(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var kc=void 0;function lc(a){throw new kc(a);}function mc(a,b,c){function d(l){l=c(l);l.length!==a.length&&lc("Mismatched type converter count");for(var m=0;m<a.length;++m)nc(a[m],l[m])}a.forEach(function(l){gc[l]=b});var e=Array(b.length),f=[],g=0;b.forEach(function(l,m){fc.hasOwnProperty(l)?e[m]=fc[l]:(f.push(l),ec.hasOwnProperty(l)||(ec[l]=[]),ec[l].push(function(){e[m]=fc[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)}
function oc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var pc=void 0;function T(a){for(var b="";A[a];)b+=pc[A[a++]];return b}var qc=void 0;function U(a){throw new qc(a);}
function nc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(fc.hasOwnProperty(a)){if(c.$b)return;U("Cannot register type '"+d+"' twice")}fc[a]=b;delete gc[a];ec.hasOwnProperty(a)&&(b=ec[a],delete ec[a],b.forEach(function(e){e()}))}function rc(a){U(a.ua.Ba.ya.name+" instance already deleted")}var sc=!1;function tc(){}
function uc(a){--a.count.value;0===a.count.value&&(a.Fa?a.Ha.Pa(a.Fa):a.Ba.ya.Pa(a.za))}function vc(a){if("undefined"===typeof FinalizationGroup)return vc=function(b){return b},a;sc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.za?uc(c):console.warn("object already deleted: "+c.za)});vc=function(b){sc.register(b,b.ua,b.ua);return b};tc=function(b){sc.unregister(b.ua)};return vc(a)}var wc=void 0,xc=[];
function yc(){for(;xc.length;){var a=xc.pop();a.ua.Ta=!1;a["delete"]()}}function zc(){}var Ac={};function Bc(a,b,c){if(void 0===a[b].Da){var d=a[b];a[b]=function(){a[b].Da.hasOwnProperty(arguments.length)||U("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Da+")!");return a[b].Da[arguments.length].apply(this,arguments)};a[b].Da=[];a[b].Da[d.cb]=d}}
function Cc(a,b,c){k.hasOwnProperty(a)?((void 0===c||void 0!==k[a].Da&&void 0!==k[a].Da[c])&&U("Cannot register public name '"+a+"' twice"),Bc(k,a,a),k.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),k[a].Da[c]=b):(k[a]=b,void 0!==c&&(k[a].zc=c))}function Dc(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.Ua=c;this.Pa=d;this.Ia=e;this.Ub=f;this.bb=g;this.Sb=l;this.kc=[]}
function Ec(a,b,c){for(;b!==c;)b.bb||U("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.bb(a),b=b.Ia;return a}function Fc(a,b){if(null===b)return this.tb&&U("null is not a valid "+this.name),0;b.ua||U('Cannot pass "'+Gc(b)+'" as a '+this.name);b.ua.za||U("Cannot pass deleted object as a pointer of type "+this.name);return Ec(b.ua.za,b.ua.Ba.ya,this.ya)}
function Hc(a,b){if(null===b){this.tb&&U("null is not a valid "+this.name);if(this.fb){var c=this.vb();null!==a&&a.push(this.Pa,c);return c}return 0}b.ua||U('Cannot pass "'+Gc(b)+'" as a '+this.name);b.ua.za||U("Cannot pass deleted object as a pointer of type "+this.name);!this.eb&&b.ua.Ba.eb&&U("Cannot convert argument of type "+(b.ua.Ha?b.ua.Ha.name:b.ua.Ba.name)+" to parameter type "+this.name);c=Ec(b.ua.za,b.ua.Ba.ya,this.ya);if(this.fb)switch(void 0===b.ua.Fa&&U("Passing raw pointer to smart pointer is illegal"),
this.rc){case 0:b.ua.Ha===this?c=b.ua.Fa:U("Cannot convert argument of type "+(b.ua.Ha?b.ua.Ha.name:b.ua.Ba.name)+" to parameter type "+this.name);break;case 1:c=b.ua.Fa;break;case 2:if(b.ua.Ha===this)c=b.ua.Fa;else{var d=b.clone();c=this.lc(c,V(function(){d["delete"]()}));null!==a&&a.push(this.Pa,c)}break;default:U("Unsupporting sharing policy")}return c}
function Ic(a,b){if(null===b)return this.tb&&U("null is not a valid "+this.name),0;b.ua||U('Cannot pass "'+Gc(b)+'" as a '+this.name);b.ua.za||U("Cannot pass deleted object as a pointer of type "+this.name);b.ua.Ba.eb&&U("Cannot convert argument of type "+b.ua.Ba.name+" to parameter type "+this.name);return Ec(b.ua.za,b.ua.Ba.ya,this.ya)}function Jc(a,b,c){if(b===c)return a;if(void 0===c.Ia)return null;a=Jc(a,b,c.Ia);return null===a?null:c.Sb(a)}var Kc={};
function Lc(a,b){for(void 0===b&&U("ptr should not be undefined");a.Ia;)b=a.bb(b),a=a.Ia;return Kc[b]}function Mc(a,b){b.Ba&&b.za||lc("makeClassHandle requires ptr and ptrType");!!b.Ha!==!!b.Fa&&lc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return vc(Object.create(a,{ua:{value:b}}))}
function Nc(a,b,c,d){this.name=a;this.ya=b;this.tb=c;this.eb=d;this.fb=!1;this.Pa=this.lc=this.vb=this.Hb=this.rc=this.ic=void 0;void 0!==b.Ia?this.toWireType=Hc:(this.toWireType=d?Fc:Ic,this.Ja=null)}function Oc(a,b,c){k.hasOwnProperty(a)||lc("Replacing nonexistant public symbol");void 0!==k[a].Da&&void 0!==c?k[a].Da[c]=b:(k[a]=b,k[a].cb=c)}
function Pc(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=k["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=M.get(b).apply(null,c);return d}}function W(a,b){a=T(a);var c=a.includes("j")?Pc(a,b):M.get(b);"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var Qc=void 0;function Rc(a){a=Sc(a);var b=T(a);X(a);return b}
function Tc(a,b){function c(f){e[f]||fc[f]||(gc[f]?gc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Qc(a+": "+d.map(Rc).join([", "]));}function Uc(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Vc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ic(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Wc(a,b,c,d,e){var f=b.length;2>f&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Ja){l=!0;break}var m="void"!==b[0].name,n="",q="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+hc(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var v=l?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[U,d,e,cc,b[0],b[1]];g&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);g&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(m?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=g?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Ja&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].Ja));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return Vc(n).apply(null,d)}var Xc=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Yc(a){4<a&&0===--Y[a].xb&&(Y[a]=void 0,Xc.push(a))}
function V(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Xc.length?Xc.pop():Y.length;Y[b]={xb:1,value:a};return b}}function Gc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Zc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Da[c>>2])};case 3:return function(c){return this.fromWireType(Ea[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function $c(a,b,c){switch(b){case 0:return c?function(d){return I[d]}:function(d){return A[d]};case 1:return c?function(d){return ua[d>>1]}:function(d){return E[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return K[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function ad(a){a||U("Cannot use deleted val. handle = "+a);return Y[a].value}function bd(a,b){var c=fc[a];void 0===c&&U(b+" has unknown type "+Rc(a));return c}var cd={};
function dd(a){var b=cd[a];return void 0===b?T(a):b}var ed=[];function fd(){return"object"===typeof globalThis?globalThis:Function("return this")()}function gd(a){var b=ed.length;ed.push(a);return b}function hd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=bd(F[(b>>2)+d],"parameter "+d);return c}var jd={},kd;kd=function(){return performance.now()};var ld=[],md=[];function Z(a,b){K[a>>2]=b;K[a+4>>2]=b/4294967296|0}var nd;
function od(a,b,c,d,e){function f(G){var H=0,D=0;G&&(D=u.response?u.response.byteLength:0,H=Ba(D),A.set(new Uint8Array(u.response),H));K[a+12>>2]=H;Z(a+16,D)}var g=K[a+8>>2];if(g){var l=z(g),m=a+112,n=z(m);n||(n="GET");var q=K[m+52>>2],v=K[m+56>>2],w=!!K[m+60>>2],h=K[m+68>>2],t=K[m+72>>2];g=K[m+76>>2];var x=K[m+80>>2],C=K[m+84>>2];m=K[m+88>>2];var L=!!(q&1),J=!!(q&2);q=!!(q&64);h=h?z(h):void 0;t=t?z(t):void 0;var na=x?z(x):void 0,u=new XMLHttpRequest;u.withCredentials=w;u.open(n,l,!q,h,t);q||(u.timeout=
v);u.Cc=l;u.responseType="arraybuffer";x&&u.overrideMimeType(na);if(g)for(;;){n=K[g>>2];if(!n)break;l=K[g+4>>2];if(!l)break;g+=8;n=z(n);l=z(l);u.setRequestHeader(n,l)}md.push(u);K[a+0>>2]=md.length;g=C&&m?A.slice(C,C+m):null;u.onload=function(G){f(L&&!J);var H=u.response?u.response.byteLength:0;Z(a+24,0);H&&Z(a+32,H);E[a+40>>1]=u.readyState;E[a+42>>1]=u.status;u.statusText&&B(u.statusText,A,a+44,64);200<=u.status&&300>u.status?b&&b(a,u,G):c&&c(a,u,G)};u.onerror=function(G){f(L);var H=u.status;Z(a+
24,0);Z(a+32,u.response?u.response.byteLength:0);E[a+40>>1]=u.readyState;E[a+42>>1]=H;c&&c(a,u,G)};u.ontimeout=function(G){c&&c(a,u,G)};u.onprogress=function(G){var H=L&&J&&u.response?u.response.byteLength:0,D=0;L&&J&&(D=Ba(H),A.set(new Uint8Array(u.response),D));K[a+12>>2]=D;Z(a+16,H);Z(a+24,G.loaded-H);Z(a+32,G.total);E[a+40>>1]=u.readyState;3<=u.readyState&&0===u.status&&0<G.loaded&&(u.status=200);E[a+42>>1]=u.status;u.statusText&&B(u.statusText,A,a+44,64);d&&d(a,u,G);D&&X(D)};u.onreadystatechange=
function(G){E[a+40>>1]=u.readyState;2<=u.readyState&&(E[a+42>>1]=u.status);e&&e(a,u,G)};try{u.send(g)}catch(G){c&&c(a,u,G)}}else c(a,0,"no url specified!")}function pd(a,b){if(!oa)if(b)a();else try{a()}catch(c){if(a=c,!(a instanceof qd||"unwind"===a))throw a&&"object"===typeof a&&a.stack&&r("exception thrown: "+[a,a.stack]),a;}}
function rd(a,b,c,d){var e=nd;if(e){var f=K[a+112+64>>2];f||(f=K[a+8>>2]);var g=z(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=function(){E[a+40>>1]=4;E[a+42>>1]=200;B("OK",A,a+44,64);c(a,0,g)};l.onerror=function(m){E[a+40>>1]=4;E[a+42>>1]=413;B("Payload Too Large",A,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function sd(a,b,c){var d=nd;if(d){var e=K[a+112+64>>2];e||(e=K[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(g){if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,m=Ba(l);A.set(new Uint8Array(g),m);K[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);E[a+40>>1]=4;E[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,g)}else E[a+40>>1]=4,E[a+42>>1]=404,B("Not Found",A,a+44,64),c(a,0,"no data")};f.onerror=function(g){E[a+40>>1]=4;E[a+42>>1]=404;
B("Not Found",A,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function td(a,b,c){var d=nd;if(d){var e=K[a+112+64>>2];e||(e=K[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(g){g=g.target.result;K[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);E[a+40>>1]=4;E[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,g)};f.onerror=function(g){E[a+40>>1]=4;E[a+42>>1]=404;B("Not Found",A,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}var ud={};
function vd(){if(!wd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in ud)void 0===ud[b]?delete a[b]:a[b]=ud[b];var c=[];for(b in a)c.push(b+"="+a[b]);wd=c}return wd}var wd;function xd(a,b){xd.Gb||(xd.Gb=eb());for(var c=0;c<b;c++)I[a+c>>0]=xd.Gb();return 0}function yd(a){return 0===a%4&&(0!==a%100||0===a%400)}
function zd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ad=[31,29,31,30,31,30,31,31,30,31,30,31],Bd=[31,28,31,30,31,30,31,31,30,31,30,31];function Cd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(yd(a.getFullYear())?Ad:Bd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Dd(a,b,c,d){function e(h,t,x){for(h="number"===typeof h?h.toString():h||"";h.length<t;)h=x[0]+h;return h}function f(h,t){return e(h,t,"0")}function g(h,t){function x(L){return 0>L?-1:0<L?1:0}var C;0===(C=x(h.getFullYear()-t.getFullYear()))&&0===(C=x(h.getMonth()-t.getMonth()))&&(C=x(h.getDate()-t.getDate()));return C}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function m(h){h=Cd(new Date(h.Ea+1900,0,1),h.nb);var t=new Date(h.getFullYear()+1,0,4),x=l(new Date(h.getFullYear(),0,4));t=l(t);return 0>=g(x,h)?0>=g(t,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=F[d+40>>2];d={uc:F[d>>2],tc:F[d+4>>2],lb:F[d+8>>2],ab:F[d+12>>2],Wa:F[d+16>>2],Ea:F[d+20>>2],mb:F[d+24>>2],nb:F[d+28>>2],Bc:F[d+32>>2],sc:F[d+
36>>2],vc:n?z(n):""};c=z(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");n={"%a":function(h){return v[h.mb].substring(0,3)},"%A":function(h){return v[h.mb]},"%b":function(h){return w[h.Wa].substring(0,3)},"%B":function(h){return w[h.Wa]},"%C":function(h){return f((h.Ea+1900)/100|0,2)},"%d":function(h){return f(h.ab,2)},"%e":function(h){return e(h.ab,2," ")},"%g":function(h){return m(h).toString().substring(2)},"%G":function(h){return m(h)},"%H":function(h){return f(h.lb,
2)},"%I":function(h){h=h.lb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){return f(h.ab+zd(yd(h.Ea+1900)?Ad:Bd,h.Wa-1),3)},"%m":function(h){return f(h.Wa+1,2)},"%M":function(h){return f(h.tc,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.lb&&12>h.lb?"AM":"PM"},"%S":function(h){return f(h.uc,2)},"%t":function(){return"\t"},"%u":function(h){return h.mb||7},"%U":function(h){var t=new Date(h.Ea+1900,0,1),x=0===t.getDay()?t:Cd(t,7-t.getDay());h=new Date(h.Ea+1900,h.Wa,h.ab);return 0>
g(x,h)?f(Math.ceil((31-x.getDate()+(zd(yd(h.getFullYear())?Ad:Bd,h.getMonth()-1)-31)+h.getDate())/7),2):0===g(x,t)?"01":"00"},"%V":function(h){var t=new Date(h.Ea+1901,0,4),x=l(new Date(h.Ea+1900,0,4));t=l(t);var C=Cd(new Date(h.Ea+1900,0,1),h.nb);return 0>g(C,x)?"53":0>=g(t,C)?"01":f(Math.ceil((x.getFullYear()<h.Ea+1900?h.nb+32-x.getDate():h.nb+1-x.getDate())/7),2)},"%w":function(h){return h.mb},"%W":function(h){var t=new Date(h.Ea,0,1),x=1===t.getDay()?t:Cd(t,0===t.getDay()?1:7-t.getDay()+1);h=
new Date(h.Ea+1900,h.Wa,h.ab);return 0>g(x,h)?f(Math.ceil((31-x.getDate()+(zd(yd(h.getFullYear())?Ad:Bd,h.getMonth()-1)-31)+h.getDate())/7),2):0===g(x,t)?"01":"00"},"%y":function(h){return(h.Ea+1900).toString().substring(2)},"%Y":function(h){return h.Ea+1900},"%z":function(h){h=h.sc;var t=0<=h;h=Math.abs(h)/60;return(t?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.vc},"%%":function(){return"%"}};for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));q=kb(c,
!1);if(q.length>b)return 0;I.set(q,a);return q.length-1}function Fb(a,b,c,d){a||(a=this);this.parent=a;this.Oa=a.Oa;this.ib=null;this.id=wb++;this.name=b;this.mode=c;this.va={};this.wa={};this.Za=d}Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Tb();xb=Array(4096);Mb(R,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");ib(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Ob("/dev/null",259);hb(1280,lb);hb(1536,mb);Ob("/dev/tty",1280);Ob("/dev/tty1",1536);var a=eb();Wb("random",a);Wb("urandom",a);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");Mb({Oa:function(){var b=qb(a,"fd",16895,73);b.va={Xa:function(c,d){var e=vb[+d];if(!e)throw new Q(8);c={parent:null,Oa:{Fb:"fake"},va:{$a:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();kc=k.InternalError=jc("InternalError");for(var Ed=Array(256),Fd=0;256>Fd;++Fd)Ed[Fd]=String.fromCharCode(Fd);pc=Ed;qc=k.BindingError=jc("BindingError");
zc.prototype.isAliasOf=function(a){if(!(this instanceof zc&&a instanceof zc))return!1;var b=this.ua.Ba.ya,c=this.ua.za,d=a.ua.Ba.ya;for(a=a.ua.za;b.Ia;)c=b.bb(c),b=b.Ia;for(;d.Ia;)a=d.bb(a),d=d.Ia;return b===d&&c===a};
zc.prototype.clone=function(){this.ua.za||rc(this);if(this.ua.Ya)return this.ua.count.value+=1,this;var a=vc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.ua;a=a(c.call(b,d,{ua:{value:{count:e.count,Ta:e.Ta,Ya:e.Ya,za:e.za,Ba:e.Ba,Fa:e.Fa,Ha:e.Ha}}}));a.ua.count.value+=1;a.ua.Ta=!1;return a};zc.prototype["delete"]=function(){this.ua.za||rc(this);this.ua.Ta&&!this.ua.Ya&&U("Object already scheduled for deletion");tc(this);uc(this.ua);this.ua.Ya||(this.ua.Fa=void 0,this.ua.za=void 0)};
zc.prototype.isDeleted=function(){return!this.ua.za};zc.prototype.deleteLater=function(){this.ua.za||rc(this);this.ua.Ta&&!this.ua.Ya&&U("Object already scheduled for deletion");xc.push(this);1===xc.length&&wc&&wc(yc);this.ua.Ta=!0;return this};Nc.prototype.Vb=function(a){this.Hb&&(a=this.Hb(a));return a};Nc.prototype.Ab=function(a){this.Pa&&this.Pa(a)};Nc.prototype.argPackAdvance=8;Nc.prototype.readValueFromPointer=dc;Nc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Nc.prototype.fromWireType=function(a){function b(){return this.fb?Mc(this.ya.Ua,{Ba:this.ic,za:c,Ha:this,Fa:a}):Mc(this.ya.Ua,{Ba:this,za:a})}var c=this.Vb(a);if(!c)return this.Ab(a),null;var d=Lc(this.ya,c);if(void 0!==d){if(0===d.ua.count.value)return d.ua.za=c,d.ua.Fa=a,d.clone();d=d.clone();this.Ab(a);return d}d=this.ya.Ub(c);d=Ac[d];if(!d)return b.call(this);d=this.eb?d.Pb:d.pointerType;var e=Jc(c,this.ya,d.ya);return null===e?b.call(this):this.fb?Mc(d.ya.Ua,{Ba:d,za:e,Ha:this,Fa:a}):Mc(d.ya.Ua,
{Ba:d,za:e})};k.getInheritedInstanceCount=function(){return Object.keys(Kc).length};k.getLiveInheritedInstances=function(){var a=[],b;for(b in Kc)Kc.hasOwnProperty(b)&&a.push(Kc[b]);return a};k.flushPendingDeletes=yc;k.setDelayFunction=function(a){wc=a;xc.length&&wc&&wc(yc)};Qc=k.UnboundTypeError=jc("UnboundTypeError");k.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};k.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){nd=a;Pa()},function(){nd=!1;Pa()});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Oa();
function kb(a,b){var c=Array(ra(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}
var Gd={J:function(a,b){$a||($a=!0,Wa());a=new Date(1E3*F[a>>2]);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);F[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;F[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;F[b+32>>2]=a;
a=F[Za()+(a?4:0)>>2];F[b+40>>2]=a;return b},L:function(a,b,c,d,e,f){try{a:{f<<=12;var g=!1;if(0!==(d&16)&&0!==a%65536)var l=-28;else{if(0!==(d&32)){var m=nb(b);if(!m){l=-48;break a}g=!0}else{var n=vb[e];if(!n){l=-8;break a}var q=f;if(0!==(c&2)&&0===(d&2)&&2!==(n.flags&2097155))throw new Q(2);if(1===(n.flags&2097155))throw new Q(2);if(!n.wa.hb)throw new Q(43);var v=n.wa.hb(n,a,b,q,c,d);m=v.za;g=v.ob}Zb[m]={cc:m,bc:b,ob:g,Na:e,jc:c,flags:d,offset:f};l=m}}return l}catch(w){return"undefined"!==typeof Yb&&
w instanceof Q||y(w),-w.Qa}},M:function(a,b){try{var c=Zb[a];if(0!==b&&c){if(b===c.bc){var d=vb[c.Na];d&&c.jc&2&&d&&d.wa.jb&&d.wa.jb(d,A.slice(a,a+b),c.offset,b,c.flags);Zb[a]=null;c.ob&&X(c.cc)}var e=0}else e=-28;return e}catch(f){return"undefined"!==typeof Yb&&f instanceof Q||y(f),-f.Qa}},P:function(a,b,c){$b=c;try{var d=z(a);if(c){$b+=4;var e=F[$b-4>>2]}else e=0;return Qb(d,b,e).Na}catch(f){return"undefined"!==typeof Yb&&f instanceof Q||y(f),-f.Qa}},K:function(a,b){try{a=z(a);a:{try{var c=Ab(a,
{qb:!0}).node;if(!c)throw new Q(44);if(!c.va.Ka)throw new Q(63);var d=c.va.Ka(c)}catch(f){if(f&&f.node&&bb(a)!==bb(Cb(f.node))){var e=-54;break a}throw f;}F[b>>2]=d.Rb;F[b+4>>2]=0;F[b+8>>2]=d.sb;F[b+12>>2]=d.mode;F[b+16>>2]=d.hc;F[b+20>>2]=d.uid;F[b+24>>2]=d.Zb;F[b+28>>2]=d.Za;F[b+32>>2]=0;P=[d.size>>>0,(O=d.size,1<=+Math.abs(O)?0<O?(Math.min(+Math.floor(O/4294967296),4294967295)|0)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];F[b+40>>2]=P[0];F[b+44>>2]=P[1];F[b+48>>2]=4096;F[b+52>>2]=d.Ob;
F[b+56>>2]=d.Mb.getTime()/1E3|0;F[b+60>>2]=0;F[b+64>>2]=d.ec.getTime()/1E3|0;F[b+68>>2]=0;F[b+72>>2]=d.Qb.getTime()/1E3|0;F[b+76>>2]=0;P=[d.sb>>>0,(O=d.sb,1<=+Math.abs(O)?0<O?(Math.min(+Math.floor(O/4294967296),4294967295)|0)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];F[b+80>>2]=P[0];F[b+84>>2]=P[1];e=0}return e}catch(f){return"undefined"!==typeof Yb&&f instanceof Q||y(f),-f.Qa}},c:function(a){var b=bc[a];delete bc[a];var c=b.vb,d=b.Pa,e=b.Cb,f=e.map(function(g){return g.Yb}).concat(e.map(function(g){return g.pc}));
mc([a],f,function(g){var l={};e.forEach(function(m,n){var q=g[n],v=m.Wb,w=m.Xb,h=g[n+e.length],t=m.oc,x=m.qc;l[m.Tb]={read:function(C){return q.fromWireType(v(w,C))},write:function(C,L){var J=[];t(x,C,h.toWireType(J,L));cc(J)}}});return[{name:b.name,fromWireType:function(m){var n={},q;for(q in l)n[q]=l[q].read(m);d(m);return n},toWireType:function(m,n){for(var q in l)if(!(q in n))throw new TypeError('Missing field:  "'+q+'"');var v=c();for(q in l)l[q].write(v,n[q]);null!==m&&m.push(d,v);return v},
argPackAdvance:8,readValueFromPointer:dc,Ja:d}]})},C:function(){},U:function(a,b,c,d,e){var f=oc(c);b=T(b);nc(a,{name:b,fromWireType:function(g){return!!g},toWireType:function(g,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var l=I;else if(2===c)l=ua;else if(4===c)l=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[g>>f])},Ja:null})},f:function(a,b,c,d,e,f,g,l,m,n,q,v,w){q=T(q);f=W(e,f);l&&(l=W(g,l));n&&(n=W(m,n));w=W(v,w);var h=hc(q);
Cc(h,function(){Tc("Cannot construct "+q+" due to unbound types",[d])});mc([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var x=t.ya;var C=x.Ua}else C=zc.prototype;t=ic(h,function(){if(Object.getPrototypeOf(this)!==L)throw new qc("Use 'new' to construct "+q);if(void 0===J.Ra)throw new qc(q+" has no accessible constructor");var u=J.Ra[arguments.length];if(void 0===u)throw new qc("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.Ra).toString()+
") parameters instead!");return u.apply(this,arguments)});var L=Object.create(C,{constructor:{value:t}});t.prototype=L;var J=new Dc(q,t,L,w,x,f,l,n);x=new Nc(q,J,!0,!1);C=new Nc(q+"*",J,!1,!1);var na=new Nc(q+" const*",J,!1,!0);Ac[a]={pointerType:C,Pb:na};Oc(h,t);return[x,C,na]})},g:function(a,b,c,d,e,f){0<b||y("Assertion failed: undefined");var g=Uc(b,c);e=W(d,e);mc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.ya.Ra&&(l.ya.Ra=[]);if(void 0!==l.ya.Ra[b-1])throw new qc("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.ya.Ra[b-1]=function(){Tc("Cannot construct "+l.name+" due to unbound types",g)};mc([],g,function(n){n.splice(1,0,null);l.ya.Ra[b-1]=Wc(m,n,null,e,f);return[]});return[]})},b:function(a,b,c,d,e,f,g,l){var m=Uc(c,d);b=T(b);f=W(e,f);mc([],[a],function(n){function q(){Tc("Cannot call "+v+" due to unbound types",m)}n=n[0];var v=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
l&&n.ya.kc.push(b);var w=n.ya.Ua,h=w[b];void 0===h||void 0===h.Da&&h.className!==n.name&&h.cb===c-2?(q.cb=c-2,q.className=n.name,w[b]=q):(Bc(w,b,v),w[b].Da[c-2]=q);mc([],m,function(t){t=Wc(v,t,n,f,g);void 0===w[b].Da?(t.cb=c-2,w[b]=t):w[b].Da[c-2]=t;return[]});return[]})},T:function(a,b){b=T(b);nc(a,{name:b,fromWireType:function(c){var d=Y[c].value;Yc(c);return d},toWireType:function(c,d){return V(d)},argPackAdvance:8,readValueFromPointer:dc,Ja:null})},x:function(a,b,c){c=oc(c);b=T(b);nc(a,{name:b,
fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Gc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Zc(b,c),Ja:null})},s:function(a,b,c,d,e,f){var g=Uc(b,c);a=T(a);e=W(d,e);Cc(a,function(){Tc("Cannot call "+a+" due to unbound types",g)},b-1);mc([],g,function(l){Oc(a,Wc(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},i:function(a,b,c,d,e){function f(n){return n}b=T(b);-1===
e&&(e=4294967295);var g=oc(c);if(0===d){var l=32-8*c;f=function(n){return n<<l>>>l}}var m=b.includes("unsigned");nc(a,{name:b,fromWireType:f,toWireType:function(n,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Gc(q)+'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+Gc(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:$c(b,
g,0!==d),Ja:null})},h:function(a,b,c){function d(f){f>>=2;var g=K;return new e(Ca,g[f+1],g[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);nc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{$b:!0})},y:function(a,b){b=T(b);var c="std::string"===b;nc(a,{name:b,fromWireType:function(d){var e=K[d>>2];if(c)for(var f=d+4,g=0;g<=e;++g){var l=d+4+g;if(g==e||0==A[l]){f=z(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),
m+=f;f=l+1}}else{m=Array(e);for(g=0;g<e;++g)m[g]=String.fromCharCode(A[d+4+g]);m=m.join("")}X(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var g=(c&&f?function(){return ra(e)}:function(){return e.length})(),l=Ba(4+g+1);K[l>>2]=g;if(c&&f)B(e,A,l+4,g+1);else if(f)for(f=0;f<g;++f){var m=e.charCodeAt(f);255<m&&
(X(l),U("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=m}else for(f=0;f<g;++f)A[l+4+f]=e[f];null!==d&&d.push(X,l);return l},argPackAdvance:8,readValueFromPointer:dc,Ja:function(d){X(d)}})},q:function(a,b,c){c=T(c);if(2===b){var d=ta;var e=va;var f=wa;var g=function(){return E};var l=1}else 4===b&&(d=xa,e=ya,f=za,g=function(){return K},l=2);nc(a,{name:c,fromWireType:function(m){for(var n=K[m>>2],q=g(),v,w=m+4,h=0;h<=n;++h){var t=m+4+h*b;if(h==n||0==q[t>>l])w=d(w,t-w),void 0===
v?v=w:(v+=String.fromCharCode(0),v+=w),w=t+b}X(m);return v},toWireType:function(m,n){"string"!==typeof n&&U("Cannot pass non-string to C++ string type "+c);var q=f(n),v=Ba(4+q+b);K[v>>2]=q>>l;e(n,v+4,q+b);null!==m&&m.push(X,v);return v},argPackAdvance:8,readValueFromPointer:dc,Ja:function(m){X(m)}})},d:function(a,b,c,d,e,f){bc[a]={name:T(b),vb:W(c,d),Pa:W(e,f),Cb:[]}},a:function(a,b,c,d,e,f,g,l,m,n){bc[a].Cb.push({Tb:T(b),Yb:c,Wb:W(d,e),Xb:f,pc:g,oc:W(l,m),qc:n})},V:function(a,b){b=T(b);nc(a,{ac:!0,
name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},Q:function(a){delete md[a-1]},j:function(a,b,c){a=ad(a);b=bd(b,"emval::as");var d=[],e=V(d);F[c>>2]=e;return b.toWireType(d,a)},n:function(a,b,c,d){a=ed[a];b=ad(b);c=dd(c);a(b,c,null,d)},t:Yc,_:function(a){if(0===a)return V(fd());a=dd(a);return V(fd()[a])},m:function(a,b){b=hd(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(n){return n.name}).join("_")+"$",e=["retType"],f=[c],g="",l=0;l<a-1;++l)g+=(0!==l?", ":"")+
"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+hc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+g+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.ac||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Vc(e).apply(null,f);return gd(a)},
Y:function(a){a=dd(a);return V(k[a])},k:function(a,b){a=ad(a);b=ad(b);return V(a[b])},A:function(a){4<a&&(Y[a].xb+=1)},r:function(a,b,c,d){a=ad(a);var e=jd[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var g="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)g+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";
e=(new Function("requireRegisteredType","Module","__emval_register",g+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(bd,k,V);jd[b]=e}return e(a,c,d)},ba:function(){return V([])},aa:function(a){return V(dd(a))},Z:function(){return V({})},$:function(a){cc(Y[a].value);Yc(a)},o:function(a,b,c){a=ad(a);b=ad(b);c=ad(c);a[b]=c},l:function(a,b){a=bd(a,"_emval_take_value");a=a.readValueFromPointer(b);return V(a)},p:function(){y()},v:function(a,b){if(0===a)a=Date.now();else if(1===
a||4===a)a=kd();else return-1;F[b>>2]=a/1E3|0;F[b+4>>2]=a%1E3*1E6|0;return 0},e:function(a,b,c){ld.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,ld.push(d?Ea[c++>>1]:F[c]),++c;return Ua[a].apply(null,ld)},S:function(){return!ia},D:function(a,b,c){A.copyWithin(a,b,b+c)},E:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ma.grow(Math.min(2147483648,d)-Ca.byteLength+
65535>>>16);Fa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},R:function(a,b,c,d,e){function f(D){od(D,g,n,q,m)}function g(D,Id){rd(D,Id.response,function(Ia){pd(function(){t?M.get(t)(Ia):b&&b(Ia)},H)},function(Ia){pd(function(){t?M.get(t)(Ia):b&&b(Ia)},H)})}function l(D){od(D,v,n,q,m)}function m(D){pd(function(){L?M.get(L)(D):e&&e(D)},H)}function n(D){pd(function(){x?M.get(x)(D):c&&c(D)},H)}function q(D){pd(function(){C?M.get(C)(D):d&&d(D)},H)}function v(D){pd(function(){t?M.get(t)(D):
b&&b(D)},H)}var w=a+112,h=z(w),t=K[w+36>>2],x=K[w+40>>2],C=K[w+44>>2],L=K[w+48>>2],J=K[w+52>>2],na=!!(J&4),u=!!(J&32),G=!!(J&16),H=!!(J&64);if("EM_IDB_STORE"===h)h=K[w+84>>2],rd(a,A.slice(h,h+K[w+88>>2]),v,n);else if("EM_IDB_DELETE"===h)td(a,v,n);else if(G){if(u)return 0;od(a,na?g:v,n,q,m)}else sd(a,v,u?n:na?f:l);return a},H:function(a,b){var c=0;vd().forEach(function(d,e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)I[e++>>0]=d.charCodeAt(f);I[e>>0]=0;c+=d.length+1});return 0},I:function(a,b){var c=
vd();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},X:function(a){if(!noExitRuntime){if(k.onExit)k.onExit(a);oa=!0}fa(a,new qd(a))},w:function(a){try{var b=ac(a);if(null===b.Na)throw new Q(8);b.rb&&(b.rb=null);try{b.wa.close&&b.wa.close(b)}catch(c){throw c;}finally{vb[b.Na]=null}b.Na=null;return 0}catch(c){return"undefined"!==typeof Yb&&c instanceof Q||y(c),c.Qa}},O:function(a,b,c,d){try{a:{for(var e=ac(a),f=a=0;f<c;f++){var g=F[b+(8*f+4)>>2],l=e,m=F[b+8*f>>2],
n=g,q=void 0,v=I;if(0>n||0>q)throw new Q(28);if(null===l.Na)throw new Q(8);if(1===(l.flags&2097155))throw new Q(8);if(16384===(l.node.mode&61440))throw new Q(31);if(!l.wa.read)throw new Q(28);var w="undefined"!==typeof q;if(!w)q=l.position;else if(!l.seekable)throw new Q(70);var h=l.wa.read(l,v,m,n,q);w||(l.position+=h);var t=h;if(0>t){var x=-1;break a}a+=t;if(t<g)break}x=a}F[d>>2]=x;return 0}catch(C){return"undefined"!==typeof Yb&&C instanceof Q||y(C),C.Qa}},B:function(a,b,c,d,e){try{var f=ac(a);
a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Sb(f,a,d);P=[f.position>>>0,(O=f.position,1<=+Math.abs(O)?0<O?(Math.min(+Math.floor(O/4294967296),4294967295)|0)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];F[e>>2]=P[0];F[e+4>>2]=P[1];f.rb&&0===a&&0===d&&(f.rb=null);return 0}catch(g){return"undefined"!==typeof Yb&&g instanceof Q||y(g),g.Qa}},N:function(a,b,c,d){try{a:{for(var e=ac(a),f=a=0;f<c;f++){var g=e,l=F[b+8*f>>2],m=F[b+(8*f+4)>>2],n=void 0,q=I;if(0>m||0>
n)throw new Q(28);if(null===g.Na)throw new Q(8);if(0===(g.flags&2097155))throw new Q(8);if(16384===(g.node.mode&61440))throw new Q(31);if(!g.wa.write)throw new Q(28);g.seekable&&g.flags&1024&&Sb(g,0,2);var v="undefined"!==typeof n;if(!v)n=g.position;else if(!g.seekable)throw new Q(70);var w=g.wa.write(g,q,l,m,n,void 0);v||(g.position+=w);try{if(g.path&&zb.onWriteToFile)zb.onWriteToFile(g.path)}catch(x){r("FS.trackingDelegate['onWriteToFile']('"+g.path+"') threw an exception: "+x.message)}var h=w;
if(0>h){var t=-1;break a}a+=h}t=a}F[d>>2]=t;return 0}catch(x){return"undefined"!==typeof Yb&&x instanceof Q||y(x),x.Qa}},ca:function(){var a=self.navigator.userAgent,b=ra(a)+1,c=Ba(b);B(a,A,c,b);return c},F:xd,W:function(a){$a||($a=!0,Wa());var b=new Date(F[a+20>>2]+1900,F[a+16>>2],F[a+12>>2],F[a+8>>2],F[a+4>>2],F[a>>2],0),c=F[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=e.getTimezoneOffset(),l=Math.min(g,f);0>c?F[a+32>>2]=
Number(f!=g&&l==d):0<c!=(l==d)&&(f=Math.max(g,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));F[a+24>>2]=b.getDay();F[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;F[a>>2]=b.getSeconds();F[a+4>>2]=b.getMinutes();F[a+8>>2]=b.getHours();F[a+12>>2]=b.getDate();F[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},u:function(){},z:Dd,G:function(a,b,c,d){return Dd(a,b,c,d)}};
(function(){function a(e){k.asm=e.exports;ma=k.asm.da;Fa();M=k.asm.na;Ha.unshift(k.asm.ea);Pa()}function b(e){a(e.instance)}function c(e){return Ta().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){r("failed to asynchronously prepare wasm: "+f);y(f)})}var d={a:Gd};Oa();if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return r("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return la||"function"!==typeof WebAssembly.instantiateStreaming||
Qa()||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){r("wasm streaming compile failed: "+f);r("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();k.___wasm_call_ctors=function(){return(k.___wasm_call_ctors=k.asm.ea).apply(null,arguments)};
var X=k._free=function(){return(X=k._free=k.asm.fa).apply(null,arguments)},Ba=k._malloc=function(){return(Ba=k._malloc=k.asm.ga).apply(null,arguments)},Sc=k.___getTypeName=function(){return(Sc=k.___getTypeName=k.asm.ha).apply(null,arguments)};k.___embind_register_native_and_builtin_types=function(){return(k.___embind_register_native_and_builtin_types=k.asm.ia).apply(null,arguments)};
var Za=k.__get_tzname=function(){return(Za=k.__get_tzname=k.asm.ja).apply(null,arguments)},Ya=k.__get_daylight=function(){return(Ya=k.__get_daylight=k.asm.ka).apply(null,arguments)},Xa=k.__get_timezone=function(){return(Xa=k.__get_timezone=k.asm.la).apply(null,arguments)},ob=k._memalign=function(){return(ob=k._memalign=k.asm.ma).apply(null,arguments)};k.dynCall_jiji=function(){return(k.dynCall_jiji=k.asm.oa).apply(null,arguments)};k.dynCall_ji=function(){return(k.dynCall_ji=k.asm.pa).apply(null,arguments)};
k.dynCall_viijii=function(){return(k.dynCall_viijii=k.asm.qa).apply(null,arguments)};k.dynCall_iiiiij=function(){return(k.dynCall_iiiiij=k.asm.ra).apply(null,arguments)};k.dynCall_iiiiijj=function(){return(k.dynCall_iiiiijj=k.asm.sa).apply(null,arguments)};k.dynCall_iiiiiijj=function(){return(k.dynCall_iiiiiijj=k.asm.ta).apply(null,arguments)};var Hd;function qd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Na=function Jd(){Hd||Kd();Hd||(Na=Jd)};
function Kd(){function a(){if(!Hd&&(Hd=!0,k.calledRun=!0,!oa)){k.noFSInit||Ub||(Ub=!0,Tb(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?Wb("stdin",k.stdin):Pb("/dev/tty","/dev/stdin"),k.stdout?Wb("stdout",null,k.stdout):Pb("/dev/tty","/dev/stdout"),k.stderr?Wb("stderr",null,k.stderr):Pb("/dev/tty1","/dev/stderr"),Qb("/dev/stdin",0),Qb("/dev/stdout",1),Qb("/dev/stderr",1));yb=!1;Va(Ha);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==typeof k.postRun&&
(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Ja.unshift(b)}Va(Ja)}}if(!(0<La)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ka();Va(Ga);0<La||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}k.run=Kd;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();Kd();


  return PhotoPayWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = PhotoPayWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return PhotoPayWasmSDK; });
else if (typeof exports === 'object')
  exports["PhotoPayWasmSDK"] = PhotoPayWasmSDK;
